### ISSUE TITLE
Running on 8 cores instead of 1 node (memory issue)

### ISSUE THREAD

**Issue by parlundin** [NationalGenomicsInfrastructure/ngi_pipeline#167]
in ngi_pipeline/nestor_ngi_config.yaml change threads to 8 when running only 8 cores. Otherwise you will run out of memory.

```
piper:
   # Also can be set as an environmental variable $PIPER_QSCRIPTS_DIR
   path_to_piper_qscripts: /proj/a2014205/software/piper/qscripts
   load_modules:
       - java/sun_jdk1.7.0_25
       - R/2.15.0
   sample:
       required_autosomal_coverage: 28.4
   threads: 16
```
